### ISSUE TITLE
"Failed to load plugin"

### ISSUE THREAD

**Issue by JuergenKaettnis** [aidenlx/folder-note-core#12] opened 2022-02-19 19:20 UTC
Suddenly unable to load plugin. Has there been an update? Get the above message.

**Comment by EKliptus** [comment] 2022-02-20 01:18
> Suddenly unable to load plugin. Has there been an update? Get the above message.

Same problem with obsidian v0.13.23
I think this issue is the same as https://github.com/aidenlx/folder-note-core/issues/11

**Comment by aidenlx** [comment] 2022-02-20 02:33
duplicate of #11

**Closed as completed by aidenlx** 2022-02-20 02:33 UTC
Labels: duplicate
